// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SAFIB;

namespace SAFIB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211208111155_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SAFIB.Models.Subvision", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("SubjectionID");

                    b.HasKey("ID");

                    b.HasIndex("SubjectionID");

                    b.ToTable("Subvisions");
                });

            modelBuilder.Entity("SAFIB.Models.Subvision", b =>
                {
                    b.HasOne("SAFIB.Models.Subvision", "Subjection")
                        .WithMany()
                        .HasForeignKey("SubjectionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
